name: CI Backend Spring Boot (Jacoco)
run-name: ${{ github.actor }} is testing backend

on: 
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test-and-coverage-backend:
    name: Run Spring Boot Tests & Generate Jacoco Coverage
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: back
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Java 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: temurin
          cache: maven

      - name: Run Maven tests with Jacoco
        run: mvn clean test jacoco:report

      - name: Upload backend coverage report
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report-back
          path: target/site/jacoco