name: CI Frontend Angular (Karma/Jasmine)
run-name: ${{ github.actor }} is testing out GitHub Actions
on: 
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test-and-coverage:
    name: Run Angular Tests & Generate Coverage
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: front
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      # Commenter ou installer ESLint si ng lint échoue
      #- name: Run lint
      #  run: npm run lint

      - name: Run Karma tests with coverage
        run: npm run test -- --watch=false --browsers=ChromeHeadless --code-coverage

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage