name: CI Frontend Angular (Karma/Jasmine)
run-name: ${{ github.actor }} is testing out GitHub Actions
on: 
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test-and-coverage:
    name: Run Angular Tests & Generate Coverage
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: front
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Installer les dépendances nécessaires pour ChromeHeadless
      - name: Install Chrome dependencies
        run: sudo apt-get update && sudo apt-get install -y libnss3 libatk-bridge2.0-0 libxss1 libasound2-data

      - name: Install npm dependencies
        run: npm ci

      # Lint (optionnel)
      #- name: Run lint
      #  run: npm run lint

      - name: Run Karma tests with coverage
        id: test
        run: npm run test -- --watch=false --browsers=ChromeHeadless --code-coverage


      - name: List coverage folder
        run: ls -R coverage || echo "Coverage folder not found"

      # Upload coverage report sans bloquer le workflow si le dossier n'existe pas
      - name: Upload coverage report
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage/bobapp
